import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Page2 from "@/components/page2";
import Page3 from "@/components/page3";
import Page4 from "@/components/page4";
import Page5 from "@/components/page5";
import Page6 from "@/components/page6";
import Drawing1 from "@/components/drawing1";
import Drawing2 from "@/components/drawing2";
import Drawing3 from "@/components/drawing3";
import Drawing4 from "@/components/drawing4";
import Drawing5 from "@/components/drawing5";
import Drawing6 from "@/components/drawing6";
import Drawing7 from "@/components/drawing7";
import Drawing8 from "@/components/drawing8";
import Drawing9 from "@/components/drawing9";
import Drawing10 from "@/components/drawing10";
import Drawing11 from "@/components/drawing11";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Page2 /> */}
      {/* <Page3 /> */}
      {/* <Page4 /> */}
      {/* <Page5 /> */}
      {/* <Page6 /> */}
      {/* <Drawing1 /> */}
      {/* <Drawing2 /> */}
      {/* <Drawing3 /> */}
      {/* <Drawing4 /> */}
      {/* <Drawing5 /> */}
      {/* <Drawing6 /> */}
      {/* <Drawing7 /> */}
      {/* <Drawing8 /> */}
      {/* <Drawing9 /> */}
      {/* <Drawing10 /> */}
      <Drawing11 />
    </>
  );
}
